CREATE TABLE [dbo].[Instruments]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	SHID Uniqueidentifier not null,
	InstrumentType nvarchar(100) not null,
	Symbol nvarchar(6) not null, 
	KidsRecommended bit null default 0,
	IssVolatile bit null default 0,
	[Name] nvarchar(100) not null,
	[Description] nvarchar(MAX) null,
	Categories nvarchar(MAX) null,
	RiskRating int null default 0,
	MarketPrice money not null default 0,
	UpdatedOn DateTime2 not null default GETDATE(),
	MarketID int not null FOREIGN KEY (MarketID) REFERENCES Markets(ID),
	PERatio decimal null,
	MarketCap bigint not null default 0,
	WebsiteUrl varchar(400) null, 
	GrossDividendYieldPercent real null,
	AnnualisedReturnPercent real null,
	CEO nvarchar(300) null,
	Employee int null default 0,
	FiveYearValue decimal(10,4) not null default 0,
	FiveYearPercentage decimal(10,4) not null default 0,
	FiveYearMinimum decimal(10,4) not null default 0,
	FiveYearMaximum decimal(10,4) not null default 0,
	OneYearValue decimal(10,4) not null default 0,
	OneYearPercentage decimal(10,4) not null default 0,
	OneYearMinimum decimal(10,4) not null default 0,
	OneYearMaximum decimal(10,4) not null default 0,
	SixMonthValue decimal(10,4) not null default 0,
	SixMonthPercentage decimal(10,4) not null default 0,
	SixMonthMinimum decimal(10,4) not null default 0,
	SixMonthMaximum decimal(10,4) not null default 0,
	ThreeMonthValue decimal(10,4) not null default 0,
	ThreeMonthPercentage decimal(10,4) not null default 0,
	ThreeMonthMinimum decimal(10,4) not null default 0,
	ThreeMonthMaximum decimal(10,4) not null default 0,
	OneMonthValue decimal(10,4) not null default 0,
	OneMonthPercentage decimal(10,4) not null default 0,
	OneMonthMinimum decimal(10,4) not null default 0,
	OneMonthMaximum decimal(10,4) not null default 0,
	OneWeekValue decimal(10,4) not null default 0,
	OneWeekPercentage decimal(10,4) not null default 0,
	OneWeekMinimum decimal(10,4) not null default 0,
	OneWeekMaximum decimal(10,4) not null default 0,
	OneDayValue decimal(10,4) not null default 0,
	OneDayPercentage decimal(10,4) not null default 0,
	OneDayMinimum decimal(10,4) not null default 0,
	OneDayMaximum decimal(10,4) not null default 0

)
